import type { VercelRequest, VercelResponse } from '@vercel/node';
import { ASSETS, OG_IMAGE, escapeHtml, getBaseUrl, getCommonMetaTags, CRITICAL_CSS, FONT_CSS, getErrorHtml } from './seo-utils';

// AI wallpapers page metadata
const METADATA = {
  title: 'AI Wallpapers - Artificial Intelligence Generated Art | BestFreeWallpapers',
  description: 'Explore stunning AI-generated wallpapers created with artificial intelligence. Download unique futuristic, abstract, and creative wallpapers made by AI for desktop and mobile devices.',
  route: '/ai-wallpapers',
  keywords: 'AI wallpapers, AI generated wallpapers, artificial intelligence art, AI art wallpapers, futuristic wallpapers, generated art wallpapers, machine learning art, Stable Diffusion wallpapers, Midjourney wallpapers'
};

// AI-themed OG image
const AI_OG_IMAGE = 'https://eocgtrggcalfptqhgxer.supabase.co/storage/v1/object/public/wallpapers-thumbnails/wallpaper-1772192337504-Golden_White_Bloom___Elegant_3D_Floral_Wallpaper.jpg';

function generateHtml(baseUrl: string): string {
  const canonicalUrl = `${baseUrl}${METADATA.route}`;

  // Structured data for CollectionPage with creative work info
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "name": "AI Wallpapers",
    "description": METADATA.description,
    "url": canonicalUrl,
    "about": {
      "@type": "Thing",
      "name": "AI-Generated Art",
      "description": "Wallpapers created using artificial intelligence technologies including machine learning and neural networks"
    }
  };

  // FAQ structured data for AI wallpapers
  const faqData = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What are AI wallpapers?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "AI wallpapers are images created using artificial intelligence tools like Stable Diffusion, Midjourney, and DALL-E. These wallpapers feature unique, creative designs that are generated by AI algorithms."
        }
      },
      {
        "@type": "Question",
        "name": "Are AI-generated wallpapers free to use?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes, all AI wallpapers on BestFreeWallpapers are free to download and use for personal purposes. We ensure all AI-generated content complies with usage guidelines."
        }
      },
      {
        "@type": "Question",
        "name": "What makes AI wallpapers unique?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "AI wallpapers are unique because they are generated by artificial intelligence rather than manually created. This allows for endless creative possibilities including futuristic designs, surreal landscapes, and abstract art that would be difficult to create by hand."
        }
      }
    ]
  };

  return `<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="author" content="BestFreeWallpapers Team" />
  
  <!-- AI Wallpapers Page SEO -->
  <title>${escapeHtml(METADATA.title)}</title>
  <meta name="description" content="${escapeHtml(METADATA.description)}" />
  <meta name="keywords" content="${escapeHtml(METADATA.keywords)}" />
  
  ${getCommonMetaTags(baseUrl, METADATA.route, METADATA.title, METADATA.description, METADATA.keywords)}
  
  ${FONT_CSS}
  
  ${CRITICAL_CSS}
  
  <!-- Structured Data - Collection -->
  <script type="application/ld+json">${JSON.stringify(structuredData)}</script>
  
  <!-- Structured Data - FAQ -->
  <script type="application/ld+json">${JSON.stringify(faqData)}</script>
</head>

<body style="background-color: #ffffff; color: #1f2937; margin: 0; padding: 0;">
  <div id="root" style="min-height: 100vh; background-color: inherit;"></div>
  <script type="module" crossorigin src="${ASSETS.mainJs}"></script>
  <link rel="modulepreload" crossorigin href="${ASSETS.vendorReact}" />
  <link rel="modulepreload" crossorigin href="${ASSETS.vendorSupabase}" />
  <link rel="modulepreload" crossorigin href="${ASSETS.vendorUtils}" />
  <link rel="stylesheet" crossorigin href="${ASSETS.mainCss}" />
</body>

</html>`;
}

export default async function handler(
  request: VercelRequest,
  response: VercelResponse
) {
  const baseUrl = getBaseUrl(request);

  try {
    const html = generateHtml(baseUrl);

    response.status(200);
    response.setHeader('Content-Type', 'text/html; charset=utf-8');
    response.setHeader('Cache-Control', 'public, s-maxage=3600, stale-while-revalidate=86400');
    response.send(html);

  } catch (error) {
    console.error('AI Wallpapers SEO handler error:', error);
    response.status(500);
    response.setHeader('Content-Type', 'text/html');
    response.send(getErrorHtml(500));
  }
}